version: '3'

services:
  app_shopping:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: r2dbc:mysql://shoppingdb.cbys6y4gohss.us-east-2.rds.amazonaws.com:3306/shoppingdb
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin123

